name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v5
        name: checkout

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - uses: actions/setup-java@v5
        name: set up jdk ${{matrix.java}}
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
          cache: 'maven'
          cache-dependency-path: '**/pom.xml'

      - name: build with maven
        run: mvn formatter:validate verify --file pom.xml -Dnative
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
